config/routes.rb
Rails.application.routes.draw do
  root "timelines#home"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  get '/chosetag/:menu_id/:tag_id', to: 'menu_tags#chose', as: 'chosetag'

  resources :menus do
    resources :comments, only: [:create, :destroy, :edit]
    resources :foods
    # resources :tags, only: [:new, :create]
    resources :menu_tags
  end

  resources :menus do
    member do
      put "like", to: "menus#upvote"
      put "dislike", to: "menus#downvote"
    end
  end

  resources :foods do
    member do
      put "ask", to: "foods#ask"
    end
  end

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :tags
  resources :relationships, only: [:create, :destroy]
  resources :searchs, only: [:index] do
    collection {post :search, to: "searchs#search"}
  end
end

app/views/shared/_comment_form.html.erb
<%= form_for [menu, @comment] do |f| %>
<% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>
  <div class="field">
    <%= f.text_area :content, class: "form-control", placeholder: "Viết bình luận ..."%> 
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
 <%= f.submit "Comment", class: "btn btn-sm" %>
<% end %>

app/views/shared/_notification.html.erb
<% current_user.notifications.each do |notification| %>
	<div class="notificationItem">
		<%= link_to edit_menu_path(notification.food.menu) do %>
			<%= User.find(notification.ask_user_id).name %> hỏi công thức món <%= notification.food.name %> 
			trong menu <%= notification.food.menu.menuName %> của bạn
		<% end %>
	</div>
<% end %>

app/views/shared/_search_form.html.erb
<%= form_tag searchs_path, method: :get do %>
    <div class="search-bar">
        <form method="GET" accept-charset="UTF-8" class="input-group">
        <div class="input-group add-on">
            <%= text_field_tag :q, nil, placeholder: @search_string ||= "Nhập từ khóa ...",
             id: "title", class: "search-query form-control", autofocus: "autofocus", type: "text" %>
            <div class="input-group-btn">
                <button class="btn" type="submit">
                    <span class="fa fa-search"></span>
                </button>
            </div>
        </div>
        </form>
    </div>
<% end %>

app/views/shared/_show_follow.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>menus:</b> <%= @user.menus.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate @users %>
    <% end %>
  </div>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_tag_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shared/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>menus:</b> <%= @user.menus.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>