config/routes.rb
Rails.application.routes.draw do
  root "timelines#home"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  get '/chosetag/:menu_id/:tag_id', to: 'menu_tags#chose', as: 'chosetag'

  resources :menus do
    resources :comments, only: [:create, :destroy, :edit]
    resources :foods
    # resources :tags, only: [:new, :create]
    resources :menu_tags
  end

  resources :menus do
    member do
      put "like", to: "menus#upvote"
      put "dislike", to: "menus#downvote"
    end
  end

  resources :foods do
    member do
      put "ask", to: "foods#ask"
    end
  end

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :tags
  resources :relationships, only: [:create, :destroy]
  resources :searchs, only: [:index] do
    collection {post :search, to: "searchs#search"}
  end
end

app/models/food.rb
class Food < ActiveRecord::Base
	belongs_to :menu
	validates :name, presence: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  def index
    @foods = Food.all
  end

  def show
  end

  def new
    @food = Food.new
    @menu = Menu.new
    respond_to do |format|
      format.js
    end
  end

  def edit
  end

  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def ask
    @food = Food.find(params[:id])
    @food.update(status: "1", ask_user_id: current_user.id)

    @activity = Activity.new(
      activity_type: "1",
      food_id: @food.id,
      menu_id: @food.menu.id,
      user_id: @food.menu.user.id,
      ask_user_id: current_user.id
    )
    @activity.save

    respond_to do |format|
      format.js #ask.js.erb
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :post_recipe, :status, :ask_user_id)
    end
end

app/views/foods/_food.html.erb
<% index = food_counter + 1 %>
<span class="content">
	<b><%= index %>. Tên món ăn: </b>
	<%= food.name %>
</span></br>
<span class="content">
  &nbsp;&nbsp;&nbsp;
  <b>Công thức:</b>
  <span id="ask-food-<%= food.id %>">
    <% if current_user != food.menu.user %>
      <% case food.status
         when 0 %>
          <%= link_to ask_food_path(food), remote: true, method: :put do %>
            <i class="fa fa-question-circle-o margin-r-5"></i> Hỏi công thức
          <% end %>
      <% when 1 %>
          <a><i class='fa fa-hourglass-half margin-r-5'></i> Sắp có công thức</a>
      <% end %>
    <% end %>
  </span><br>
  <div style="margin-left: 18px"><%= food.post_recipe %></div>
</span>
</br>

app/views/foods/_form.html.erb
<%= fields_for food do |form_food| %> 
    <div class="input-group col-xs-12 col-md-12" style="margin-bottom: 20px;">
        <%= form_food.label " Tên món ăn: ", class: "input-group-addon fa fa-edit", style: "width: 200px; height: 20px ;text-transform: uppercase; background: #91CB5B; color: white;" %>
        <%= form_food.text_field :name, class: "form-control", name: "food[]" %>
    </div>
    <div class="input-group col-xs-12 col-md-12" style="margin-bottom: 20px;">
        <%= form_food.label " Công thức: ", class: "input-group-addon fa fa-pencil", style: "width: 200px; height: 20px ;text-transform: uppercase; background: #91CB5B; color: white;" %>
        <%= form_food.text_area :post_recipe, class: "form-control", name: "post_recipe[]" %>
    </div>
<% end %>

app/views/foods/ask.js.erb
$("#ask-food-" + '<%= @food.id %>').html('<a><i class=\'fa fa-hourglass-half\'></i> Sắp có công thức</a>');

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Foods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/new.js.erb
$("div#foods").append("<%= j render 'form', food: @food %>");

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>