config/routes.rb
Rails.application.routes.draw do
  root "timelines#home"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  get '/chosetag/:menu_id/:tag_id', to: 'menu_tags#chose', as: 'chosetag'

  resources :menus do
    resources :comments, only: [:create, :destroy, :edit]
    resources :foods
    # resources :tags, only: [:new, :create]
    resources :menu_tags
  end

  resources :menus do
    member do
      put "like", to: "menus#upvote"
      put "dislike", to: "menus#downvote"
    end
  end

  resources :foods do
    member do
      put "ask", to: "foods#ask"
    end
  end

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :tags
  resources :relationships, only: [:create, :destroy]
  resources :searchs, only: [:index] do
    collection {post :search, to: "searchs#search"}
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  before_action :authenticate_user!
  def index
    @search = User.search name_cont: params[:q]
    @users = @search.result.paginate(page: params[:page])

    @search_menu = Menu.search menuName_cont: params[:q]
    @menus = @search_menu.result.paginate(page: params[:page])
    @search_string =  params[:q]
  end
end

app/views/searchs/_result.html.erb
<li>
  <%if object.is_a? Menu%>
    <table>
      <thead>
        <tr>
          <th>menuName</th>
          <th>Content</th>
          <th>User</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= link_to object.menuName, menu_path(object) %></td>
          <td><%= object.content %></td>
          <td><%= object.user.name %></td>
        </tr>
      </tbody>
    </table>
  <% elsif object.is_a? User %>
    <h3>Name: <%= link_to object.name, user_path(object) %></h3>
    <h3>Email: <%= object.email %></h3>
  <% end %>
</li>

app/views/searchs/index.html.erb
  <div>
    <div class="row">
      <aside class="col-md-4">
        <h1><%= current_user.name %></h1>
      </aside>
      <div class="col-md-8">
        <h3><%= "Users(#{@users.count}), Menu(#{@menus.count})" %></h3>
        <% if @users.any? %>
          <ul class="users">
            <% @users.each do |user|%>
              <%= render "result", object: user %>
            <% end %>
          </ul>
          <%= will_paginate @users%>
        <% end %>

        <% if @menus.any? %>
          <ul class="menus">
            <% @menus.each do |menu|%>
              <%= render "result", object: menu %>
            <% end %>
          </ul>
          <%= will_paginate @menus%>
        <% end %>
      </div>
    </div>
  </div>