config/routes.rb
Rails.application.routes.draw do
  root "timelines#home"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  get '/chosetag/:menu_id/:tag_id', to: 'menu_tags#chose', as: 'chosetag'

  resources :menus do
    resources :comments, only: [:create, :destroy, :edit]
    resources :foods
    # resources :tags, only: [:new, :create]
    resources :menu_tags
  end

  resources :menus do
    member do
      put "like", to: "menus#upvote"
      put "dislike", to: "menus#downvote"
    end
  end

  resources :foods do
    member do
      put "ask", to: "foods#ask"
    end
  end

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :tags
  resources :relationships, only: [:create, :destroy]
  resources :searchs, only: [:index] do
    collection {post :search, to: "searchs#search"}
  end
end

app/views/layouts/_footer.html.erb
<footer id="footer" class="nmh-footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <p class="copyright"><span class="hidden-xs hidden-sm">COPYRIGHT </span>© 2016 ANHOICHAM.</p>
            </div>
            <div class="col-sm-8">
                <ul class="footer-nav clearfix">
                    <% if user_signed_in? %>
                    <li><%= link_to "Trang chủ", root_path %></li>
                    <li><a href="#">Danh sách công thức</a></li>
                    <li><a href="#">Liên lạc</a></li>
                    <% else %>
                    <li><a href="#">Liên lạc</a></li>
                    <li><%= link_to "Đăng nhập", new_user_session_path %></li>
                    <% end %>
                </ul>
            </div>
        </div>
        <hr/>
    </div>
    <a href="#" id="back-to-top" title="Back to top" name="btn_backtoptop"></a>
    <a href="#" id="mb-postre" class="hidden-md" title="Đăng công thức mới"></a>
</footer>

app/views/layouts/_header.html.erb
<!-- BEGIN | Header -->
<header id="header" class="nmh-header ht-header">
  <nav id="navbar-primary" class="navbar navbar-fixed-top" role="navigation">
    <div class="container">
      <ul class="nav navbar-nav">
        <li class="active logo pull-left">
          <%= link_to root_path do %>
            <img src="<%= image_url('logo.png') %>" alt="logo" class="logo">
          <% end %>
        </li>
        <li class="pull-right">
          <div class="mobile-control-toggle">
            <button type="button" class="mobile-nav-toggle" data-target="#menu-list">
              <span class="sr-only">Toggle mobile menu</span>
              <span class="icon-bar icon-bar-1"></span>
              <span class="icon-bar icon-bar-2"></span>
              <span class="icon-bar icon-bar-3"></span>
            </button>
          </div>
          <!-- ./mobile-panels-control -->
          <div class="mobile-nav">
            <ul>
              <li class="current-menu-item_ menu-item-has-children_ dropdown-menu_">
                  <%= link_to "Trang chủ", root_path %>
              </li>
              <li><a href="/postrecipes" onclick="dotmetrix.track('レシピ投稿画面に遷移');">Đăng công thức</a></li>
              <li><a href="/recipes">Công thức nấu ăn</a></li>
              <li><a href="/contact">Liên hệ</a></li>
              <li><a href="/login" data-toggle="modal_" data-target="#ht-lre_">Đăng nhập</a></li>
            </ul>
          </div>
          <!-- / .mobile-nav -->
      </li>
      <li class="pull-right">
          <div class="ht-main-navbar nmh-main-navbar">
            <nav id="ht-main-nav">
              <ul class="menu-bar">
                <% if user_signed_in? %>
                  <li>
                    <%= link_to "Trang chủ", root_path %>
                  </li>
                  <li><%= link_to  "Tag của bạn", tags_path %></li>
                  <li><%= link_to  "Thực đơn của bạn", menus_path %></li>
                  <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <i class="fa fa-bell"></i>
                    </a>
                    <div class="notificationContainer dropdown-menu">
                      <div class="notificationTitle">Thông báo</div>
                      <div class="notificationsBody">
                        <%= render "shared/notification" %>
                      </div>
                      <div class="notificationFooter"><a class="notify-all">Xem tất cả</a></div>
                    </div>
                  </li>
                  <li class="menu-item-has-children dropdown login-f pull-right">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <img> <%= image_tag current_user.avatar.url, class: "avatar", width: "36px", height: "36px", id:"avatar" %> 
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to current_user.name, current_user %></li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Đăng xuất", destroy_user_session_path, method: :delete, class: "btn btn-link" %>
                      </li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Chỉnh sửa thông tin cá nhân", edit_user_registration_path %>
                      </li>
                    </ul>
                  </li>
                  <% else %>
                  <li class="pull-right">
                    <%= link_to "Đăng ký", new_user_registration_path %>
                  </li>
                <% end %>
              </ul>
          </nav>
        </div>
    </li>
      </ul><!-- /.navbar-nav -->
    </div><!-- /.container -->
  </nav>
    <div class="search-bar-wrap">
      <div class="container">
        <% if user_signed_in? %>
          <div class="row">
            <div class="col-md-8">
              <%= render "shared/search_form" %>
            </div>
            <div class="col-md-4">
              <div class="post-recipe-button">
                <%= link_to new_menu_path, class: "btn btn-block btn-post-recipe" do %>
                  Đăng thực đơn
                <span class="fa fa-upload"></span>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <script>
        $('.notificationLink').click(function() {
            $('.notificationContainer').toggleClass('hide');
        })

        $().ready(function() {
            var nextElement = $('#header').next();
            var ckEle = nextElement.is('style', 'script', 'section');
            if (!ckEle) {
                nextElement.addClass('content-position');
            }
        });

        $(window).scroll(function () {
            if ($(this).scrollTop() > 600) {
                $('#navbar-primary').addClass("sticky");
            } else {
                $('#navbar-primary').removeClass("sticky");
            }
        });
    </script>
</header>
<!-- END | Header -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <title><%= yield :title %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
    <!-- Mobile specific meta -->
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="format-detection" content="telephone-no">
    <meta name="google-site-verification" content="ljVic1zd3ToZkdWh_99Nc70r_WLDuDQS24hwxNa2NTo" />
    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Raleway:300,400,700,900' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Dosis:700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700&subset=latin,vietnamese'
          rel='stylesheet' type='text/css'>
</head>
<body class="">

<div class="ht-page-wrapper nmh-page-wrapper">
    <%= render "layouts/header" %>
    <div class="container" style="min-height: 500px; padding: 220px 0;">
        <div class="col-md-12">
            <%= yield %>
        </div>
    </div>
</div>

<%= javascript_include_tag 'custom.js' %>
</body>

</html>